import { Browser } from "@/components/apps/Browser";
import Calculator from "@/components/apps/Calculator";
import Camera from "@/components/apps/Camera";
import Clock from "@/components/apps/Clock";
import Settings from "@/components/apps/Settings";
import Files from "@/components/apps/Files";

const TASKBAR_APPS = [
  {
    id: 1,
    name: "Chrome",
    icon: "./images/apps/chrome.svg",
    iconShape: "circle", // Polos tanpa bg putih
    link: "",
    isMinimized: false,
    render: <Browser link={"https://www.google.com/webhp?igu=1"} isChrome={true} />,
  },
  {
    id: 2,
    name: "Gmail",
    icon: "./images/apps/gmail.svg",
    iconShape: "non-circle", // Pakai bg putih bulat
    link: "",
    isMinimized: false,
    render: <Browser link={"https://mail.google.com"} />,
  },
  {
    id: 3,
    name: "Calendar",
    icon: "./images/apps/calendar.svg",
    iconShape: "non-circle", // Pakai bg putih bulat
    link: "",
    isMinimized: false,
    render: <Browser link={"https://calendar.google.com"} />,
  },
  {
    id: 4,
    name: "Photos",
    icon: "./images/apps/photos.svg",
    iconShape: "non-circle", // Pakai bg putih bulat
    link: "",
    isMinimized: false,
    render: <Browser link={"https://photos.google.com"} />,
  },
  {
    id: 5,
    name: "Docs",
    icon: "./images/apps/docs.svg",
    iconShape: "non-circle", // Pakai bg putih bulat
    link: "",
    isMinimized: false,
    render: <Browser link={"https://docs.google.com"} />,
  },
  {
    id: 21,
    name: "Gemini",
    icon: "./images/apps/gemini.png",
    iconShape: "non-circle",
    link: "",
    isMinimized: false,
    render: <Browser link={"https://gemini.google.com"} />,
  },
];

const STAR_MENU_DEFAULT_APPS = [
  {
    id: 1,
    name: "Chrome",
    icon: "./images/apps/chrome.svg",
    iconShape: "circle",
    link: "",
    isMinimized: false,
    render: <Browser link={"https://www.google.com/webhp?igu=1"} isChrome={true} />,
  },
  {
    id: 2,
    name: "Gmail",
    icon: "./images/apps/gmail.svg",
    iconShape: "non-circle",
    link: "",
    isMinimized: false,
    render: <Browser link={"https://mail.google.com"} />,
  },
  {
    id: 3,
    name: "Calendar",
    icon: "./images/apps/calendar.svg",
    iconShape: "non-circle",
    link: "",
    isMinimized: false,
    render: <Browser link={"https://calendar.google.com"} />,
  },
  {
    id: 4,
    name: "Photos",
    icon: "./images/apps/photos.svg",
    iconShape: "non-circle",
    link: "",
    isMinimized: false,
    render: <Browser link={"https://photos.google.com"} />,
  },
  {
    id: 5,
    name: "Docs",
    icon: "./images/apps/docs.svg",
    iconShape: "non-circle",
    link: "",
    isMinimized: false,
    render: <Browser link={"https://docs.google.com"} />,
  },
];

const STAR_MENU_APPS = [
  {
    id: 1,
    name: "Chrome",
    icon: "./images/apps/chrome.svg",
    iconShape: "circle",
    link: "",
    isMinimized: false,
    render: <Browser link={"https://www.google.com/webhp?igu=1"} isChrome={true} />,
  },
  {
    id: 2,
    name: "Gmail",
    icon: "./images/apps/gmail.svg",
    iconShape: "non-circle",
    link: "",
    isMinimized: false,
    render: <Browser link={"https://mail.google.com"} />,
  },
  {
    id: 3,
    name: "Calendar",
    icon: "./images/apps/calendar.svg",
    iconShape: "non-circle",
    link: "",
    isMinimized: false,
    render: <Browser link={"https://calendar.google.com"} />,
  },
  {
    id: 4,
    name: "Photos",
    icon: "./images/apps/photos.svg",
    iconShape: "non-circle",
    link: "",
    isMinimized: false,
    render: <Browser link={"https://photos.google.com"} />,
  },
  {
    id: 5,
    name: "Docs",
    icon: "./images/apps/docs.svg",
    iconShape: "non-circle",
    link: "",
    isMinimized: false,
    render: <Browser link={"https://docs.google.com"} />,
  },
  {
    id: 9,
    name: "Calculator",
    icon: "./images/apps/calculator.svg",
    iconShape: "circle",
    link: "",
    isMinimized: false,
    render: <Calculator />,
    defaultSize: { width: 320, height: 500 }
  },
  {
    id: 10,
    name: "Camera",
    icon: "./images/apps/camera.svg",
    iconShape: "non-circle",
    link: "",
    isMinimized: false,
    render: <Camera />,
  },
  {
    id: 11,
    name: "Clock",
    icon: "./images/apps/clock.svg",
    iconShape: "circle",
    link: "",
    isMinimized: false,
    render: <Clock />,
  },
  {
    id: 12,
    name: "Drive",
    icon: "./images/apps/drive.svg",
    iconShape: "non-circle",
    link: "",
    isMinimized: false,
    render: <Browser link={"https://drive.google.com"} />,
  },
  {
    id: 13,
    name: "Earth",
    icon: "./images/apps/earth.svg",
    iconShape: "circle",
    link: "",
    isMinimized: false,
    render: <Browser link={"https://earth.google.com"} />,
  },
  {
    id: 14,
    name: "Instagram",
    icon: "./images/apps/instagram.svg",
    iconShape: "non-circle",
    link: "",
    isMinimized: false,
  },
  {
    id: 15,
    name: "Keep",
    icon: "./images/apps/keep.svg",
    iconShape: "non-circle",
    link: "",
    isMinimized: false,
    render: <Browser link={"https://keep.google.com"} />,
  },
  {
    id: 16,
    name: "Maps",
    icon: "./images/apps/maps.svg",
    iconShape: "non-circle",
    link: "",
    isMinimized: false,
    render: <Browser link={"https://maps.google.com"} />,
  },
  {
    id: 17,
    name: "Meet",
    icon: "./images/apps/meet.svg",
    iconShape: "non-circle",
    link: "",
    isMinimized: false,
    render: <Browser link={"https://meet.google.com"} />,
  },
  {
    id: 18,
    name: "Messenger",
    icon: "./images/apps/messenger.svg",
    iconShape: "non-circle",
    link: "",
    isMinimized: false,
  },
  {
    id: 7,
    name: "Youtube",
    icon: "./images/apps/youtube.svg",
    iconShape: "non-circle", // Di menu launcher biar konsisten pake bg juga atau sesuaikan
    link: "",
    isMinimized: false,
    render: <Browser link={"https://youtube.com"} />,
  },
  {
    id: 19,
    name: "Twitter",
    icon: "./images/apps/twitter.svg",
    iconShape: "non-circle",
    link: "",
    isMinimized: false,
  },
  {
    id: 20,
    name: "Play Games",
    icon: "./images/apps/Play_Games.svg",
    iconShape: "non-circle",
    link: "",
    isMinimized: false,
  },
  {
    id: 6,
    name: "Files",
    icon: "./images/apps/files.svg",
    iconShape: "circle",
    link: "",
    isMinimized: false,
    render: <Files />,
  },
  {
    id: 8,
    name: "Settings",
    icon: "./images/apps/settings.svg",
    iconShape: "circle",
    link: "",
    isMinimized: false,
    render: <Settings />,
  },
  {
    id: 21,
    name: "Gemini",
    icon: "./images/apps/gemini.png",
    iconShape: "non-circle",
    link: "",
    isMinimized: false,
    render: <Browser link={"https://gemini.google.com"} />,
  },
  {
    id: 22,
    name: "Youtube Music",
    icon: "./images/apps/youtube_music.svg",
    iconShape: "non-circle",
    link: "",
    isMinimized: false,
    render: <Browser link={"https://music.youtube.com"} />,
  },
];

export { TASKBAR_APPS, STAR_MENU_DEFAULT_APPS, STAR_MENU_APPS };